version: 2
jobs:
    build:
        machine: true
        steps:
            - checkout
            - run: |
                docker info
                if [[ -e ~/docker/image.tar ]]; then docker load --input ~/docker/image.tar; fi
                docker build --rm=false -t panoramatwelve/selftrigger:latest .
                mkdir -p ~/docker; docker save panoramatwelve/selftrigger:latest > ~/docker/image.tar
            - run: |
                mkdir /tmp/logs
#                docker run -d panoramatwelve/selftrigger:latest "cd /etc" > /tmp/logs/dockerrun.log 2>&1
#                cat /tmp/logs/dockerrun.log
            - run: |
                mkdir /tmp/artifacts
                ulimit -c unlimited
                docker save panoramatwelve/selftrigger:latest > /tmp/artifacts/selftrigger.docker.tar
            - run: |
                docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
                docker push panoramatwelve/selftrigger:latest
            - store_artifacts:
                path: /tmp/artifacts
            - store_artifacts:
                path: /tmp/logs
