version: 2
jobs:
    build:
        machine: true
        steps:
            - checkout
            - run: |
                docker info
                mkdir /tmp/artifacts
                mkdir /tmp/logs
                ulimit -c unlimited
                docker run -it -w /usr/workspace -v $(pwd):/usr/workspace -e LOGIN_MINE_USERNAME=$LOGIN_MINE_USERNAME -e LOGIN_MINE_PW=$LOGIN_MINE_PW joyzoursky/python-chromedriver:3.7 "./scripts/execute_automation.sh" > /tmp/logs/dockerrun.log 2>&1
                mv *.png /tmp/artifacts/
            - store_artifacts:
                path: /tmp/artifacts
            - store_artifacts:
                path: /tmp/logs

